apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: amondu
spec:
  selector:
    app: edtech-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer  # 외부 IP 할당 (Azure에서 Public IP 생성됨)
