apiVersion: v1
kind: Service
metadata:
  name: attention-service
  namespace: amondu
spec:
  selector:
    app: attention-model-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
